/**
 * Generates the database documentation from the Prisma schema:
 *
 *   docs/database/README.md        bounded contexts, owners and the context map
 *   docs/database/<context>.md     Mermaid ER diagram + column reference per context
 *
 *   pnpm docs:erd
 *
 * Relations exist only inside a context; references across contexts are plain
 * ids kept consistent by events. Those logical references are inferred from
 * field names (tenantId, outletId, ...) and drawn as dashed edges in the map.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { getDMMF } from '@prisma/internals';

type DMMF = Awaited<ReturnType<typeof getDMMF>>;
type Model = DMMF['datamodel']['models'][number] & {
  schema?: string | null;
  documentation?: string;
};
type Field = Model['fields'][number] & { documentation?: string };

const root = path.resolve(__dirname, '../../..');
const schemaDir = path.resolve(__dirname, '../prisma/schema');
const outDir = path.join(root, 'docs', 'database');

const OWNERS: Record<string, string> = {
  identity: 'auth-service, user-service',
  commerce: 'order-service',
  payments: 'payment-service',
  delivery: 'delivery-service',
  inventory: 'inventory-service',
  procurement: 'procurement-service',
  marketplace: 'supplier-service',
  analytics: 'analytics-service',
  ads: 'ads-service',
  notifications: 'notification-service',
  ai: 'ai-service',
  platform: 'shared (outbox, idempotency, sequences)',
};

/** Logical (cross-context) references by field name -> target model. */
const LOGICAL_REFS: Record<string, string> = {
  tenantId: 'Tenant',
  buyerTenantId: 'Tenant',
  sellerTenantId: 'Tenant',
  supplierTenantId: 'Tenant',
  dealerTenantId: 'Tenant',
  userId: 'User',
  customerId: 'User',
  approverId: 'User',
  outletId: 'Outlet',
  orderId: 'Order',
  menuItemId: 'MenuItem',
  riderId: 'RiderProfile',
  deliveryId: 'Delivery',
  ingredientId: 'Ingredient',
  productId: 'Product',
  purchaseOrderId: 'PurchaseOrder',
  sourcePurchaseOrderId: 'PurchaseOrder',
  b2bOrderId: 'B2bOrder',
  paymentId: 'Payment',
  campaignId: 'AdCampaign',
  mealSubscriptionId: 'MealSubscription',
  zoneId: 'DeliveryZone',
};

/** Context-specific exceptions to the naming convention above. */
const LOGICAL_REF_OVERRIDES: Record<string, string> = {
  'notifications.campaignId': 'PushCampaign',
};

const mermaidType = (f: Field) =>
  `${f.type}${f.isList ? '_list' : ''}`.replace(/[^A-Za-z0-9_]/g, '_');
const esc = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function defaultOf(f: Field): string {
  const d = (f as { default?: unknown }).default;
  if (d === undefined) return '';
  if (typeof d === 'object' && d !== null && 'name' in d)
    return `${(d as { name: string }).name}()`;
  return Array.isArray(d) ? `[${d.join(', ')}]` : String(d);
}

async function main() {
  const files = readdirSync(schemaDir)
    .filter((f) => f.endsWith('.prisma'))
    .map(
      (f) =>
        [path.join(schemaDir, f), readFileSync(path.join(schemaDir, f), 'utf8')] as [
          string,
          string,
        ],
    );
  const dmmf = await getDMMF({ datamodel: files });
  const models = dmmf.datamodel.models as Model[];
  const contextOf = new Map(models.map((m) => [m.name, m.schema ?? 'public']));
  const contexts = [...new Set(models.map((m) => m.schema ?? 'public'))].sort(
    (a, b) => Object.keys(OWNERS).indexOf(a) - Object.keys(OWNERS).indexOf(b),
  );
  const enumNames = new Set(dmmf.datamodel.enums.map((e) => e.name));
  mkdirSync(outDir, { recursive: true });

  // logical references between contexts
  const edges = new Map<string, Set<string>>();
  const logicalRefs = new Map<string, { field: string; target: string }[]>();
  for (const m of models) {
    const fkFields = new Set(
      m.fields.flatMap((f) => (f.relationFromFields as string[] | undefined) ?? []),
    );
    for (const f of m.fields) {
      const target = LOGICAL_REF_OVERRIDES[`${m.schema}.${f.name}`] ?? LOGICAL_REFS[f.name];
      if (
        f.kind !== 'scalar' ||
        !target ||
        fkFields.has(f.name) ||
        target === m.name ||
        !contextOf.has(target)
      )
        continue;
      const from = contextOf.get(m.name)!;
      const to = contextOf.get(target)!;
      logicalRefs.set(m.name, [
        ...(logicalRefs.get(m.name) ?? []),
        { field: f.name, target: `${to}.${target}` },
      ]);
      if (from === to) continue;
      const key = `${from}|${to}`;
      edges.set(key, (edges.get(key) ?? new Set()).add(f.name));
    }
  }

  // ── overview ──────────────────────────────────────────────────────────────
  const overview: string[] = [
    '# FoodGrid data model',
    '',
    'Generated by `pnpm docs:erd` from `packages/database/prisma/schema` — do not edit by hand.',
    '',
    `${models.length} models and ${dmmf.datamodel.enums.length} enums in ${contexts.length} PostgreSQL schemas, one per bounded context. Foreign keys exist only within a context; references across contexts are plain ids kept consistent through domain events (transactional outbox → Redis Streams), so any context can move to its own database.`,
    '',
    '| Context (schema) | Owner | Models |',
    '| --- | --- | ---: |',
    ...contexts.map(
      (c) =>
        `| [${c}](./${c}.md) | ${OWNERS[c] ?? ''} | ${models.filter((m) => (m.schema ?? 'public') === c).length} |`,
    ),
    '',
    '## Context map',
    '',
    'Dashed edges are logical id references (no foreign key), labelled with the referencing fields.',
    '',
    '```mermaid',
    'flowchart LR',
    ...contexts.map((c) => `  ${c}["${c}<br/><small>${OWNERS[c] ?? ''}</small>"]`),
    ...[...edges.entries()].sort().map(([k, fields]) => {
      const [from, to] = k.split('|');
      return `  ${from} -. "${[...fields].sort().join(', ')}" .-> ${to}`;
    }),
    '```',
    '',
  ];
  writeFileSync(path.join(outDir, 'README.md'), overview.join('\n'));

  // ── per context ───────────────────────────────────────────────────────────
  for (const ctx of contexts) {
    const inCtx = models
      .filter((m) => (m.schema ?? 'public') === ctx)
      .sort((a, b) => a.name.localeCompare(b.name));
    const lines: string[] = [
      `# \`${ctx}\` schema`,
      '',
      `Owner: ${OWNERS[ctx] ?? 'n/a'} · ${inCtx.length} models · [all contexts](./README.md)`,
      '',
      'The diagram shows keys and relations; every column is listed in the reference below.',
      '',
      '```mermaid',
      'erDiagram',
    ];
    const rels = new Set<string>();
    for (const m of inCtx) {
      const fkFields = new Set(
        m.fields.flatMap((f) => (f.relationFromFields as string[] | undefined) ?? []),
      );
      const uniques = new Set(m.fields.filter((f) => f.isUnique).map((f) => f.name));
      lines.push(`  ${m.name} {`);
      for (const f of m.fields) {
        if (f.kind === 'object') continue;
        const keys = [
          f.isId || m.primaryKey?.fields.includes(f.name) ? 'PK' : '',
          fkFields.has(f.name) ? 'FK' : '',
          uniques.has(f.name) ? 'UK' : '',
        ].filter(Boolean);
        const logical = logicalRefs.get(m.name)?.find((r) => r.field === f.name);
        if (!keys.length && !logical) continue;
        lines.push(
          `    ${mermaidType(f)} ${f.name}${keys.length ? ` ${keys.join(', ')}` : ''}${logical && !keys.includes('FK') ? ` "-> ${logical.target}"` : ''}`,
        );
      }
      lines.push('  }');
      for (const f of m.fields) {
        if (f.kind !== 'object' || !f.relationFromFields?.length) continue;
        const target = models.find((x) => x.name === f.type)!;
        const back = target.fields.find(
          (x) => x.relationName === f.relationName && x.type === m.name && x !== f,
        );
        const many = back?.isList ?? true;
        const childOptional = !f.isRequired;
        const card = `${childOptional ? '|o' : '||'}--${many ? 'o{' : 'o|'}`;
        rels.add(`  ${target.name} ${card} ${m.name} : "${f.name}"`);
      }
    }
    lines.push(...[...rels].sort(), '```', '');

    for (const m of inCtx) {
      lines.push(`## ${m.name}`, '');
      if (m.documentation) lines.push(m.documentation, '');
      lines.push(
        `Table \`${ctx}."${m.dbName ?? m.name}"\``,
        '',
        '| Column | Type | Null | Default | Notes |',
        '| --- | --- | :---: | --- | --- |',
      );
      for (const f of m.fields) {
        if (f.kind === 'object') continue;
        const type = `${enumNames.has(f.type) ? `enum ${f.type}` : f.type}${f.isList ? '[]' : ''}`;
        const notes = [
          f.isId ? 'PK' : '',
          f.isUnique ? 'unique' : '',
          logicalRefs.get(m.name)?.find((r) => r.field === f.name)
            ? `→ ${logicalRefs.get(m.name)!.find((r) => r.field === f.name)!.target}`
            : '',
          (f as Field).documentation ?? '',
        ].filter(Boolean);
        lines.push(
          `| \`${f.name}\` | ${type} | ${f.isRequired ? '' : '✓'} | ${esc(defaultOf(f as Field))} | ${esc(notes.join('; '))} |`,
        );
      }
      const indexes = [
        ...(m.primaryKey && m.primaryKey.fields.length > 1
          ? [`primary key (${m.primaryKey.fields.join(', ')})`]
          : []),
        ...m.uniqueFields.map((u) => `unique (${u.join(', ')})`),
      ];
      if (indexes.length) lines.push('', `Constraints: ${indexes.join('; ')}`);
      lines.push('');
    }
    writeFileSync(path.join(outDir, `${ctx}.md`), lines.join('\n'));
  }
  console.log(
    `ERD for ${models.length} models in ${contexts.length} contexts written to ${path.relative(root, outDir)}/`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
