import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'helpers.dart';

Map<String, dynamic> _po(String status) => {
      'id': 'po1',
      'poNumber': 'PO-261007-00001',
      'outletId': 'o1',
      'supplierTenantId': 's1',
      'supplierName': 'Cowberry Dairy Distributors',
      'status': status,
      'source': 'AUTO_REORDER',
      'subtotal': '1350',
      'taxTotal': '67.5',
      'deliveryCharge': '0',
      'total': '1417.5',
      'paymentTerms': 'NET_7',
      'expectedDeliveryAt': '2026-10-08T04:30:00.000Z',
      'notes': 'Generated by the smart procurement engine from open reorder alerts.',
      'supplierNotes': null,
      'trackingInfo': null,
      'createdAt': '2026-10-07T00:40:00.000Z',
      'items': [
        {'id': 'pi1', 'name': 'Set Curd 5 kg Bucket', 'quantity': '3', 'unit': '5 KG', 'unitPrice': '325', 'gstRate': '5', 'lineTotal': '975', 'confirmedQty': null, 'receivedQty': '0'},
        {'id': 'pi2', 'name': 'Frozen Green Peas 1 kg', 'quantity': '3', 'unit': '1 KG', 'unitPrice': '125', 'gstRate': '5', 'lineTotal': '375', 'confirmedQty': null, 'receivedQty': '0'},
      ],
      'events': [
        {'id': 'e1', 'status': 'PENDING_APPROVAL', 'note': 'Above auto-approval limit', 'createdAt': '2026-10-07T00:40:00.000Z'},
      ],
    };

FakeBackend _backend() {
  final b = baseBackend();
  b.get('/procurement/dashboard', {'openAlerts': {'CRITICAL': 1, 'LOW': 1}, 'pendingApproval': 1, 'awaitingSupplier': 0, 'inTransit': 0, 'deliveredNotReceived': 0, 'monthToDateSpend': 42244.53});
  b.on('GET', '/procurement/purchase-orders', (o) {
    final statuses = o.queryParameters['status'] as List;
    return page(statuses.contains('PENDING_APPROVAL') ? [_po('PENDING_APPROVAL')] : const []);
  });
  b.get('/procurement/purchase-orders/po1', _po('PENDING_APPROVAL'));
  b.get('/procurement/alerts', [
    {
      'id': 'al1',
      'outletId': 'o1',
      'ingredientId': 'ing1',
      'ingredientName': 'Tomato',
      'category': 'VEGETABLES',
      'unit': 'KG',
      'currentStock': '2',
      'reorderLevel': '5.727',
      'avgDailyUsage': '3.818',
      'daysOfCover': 0.5,
      'predictedDepletionDate': '2026-10-07T08:38:06.595Z',
      'suggestedQty': '15.18',
      'severity': 'CRITICAL',
      'status': 'OPEN',
      'purchaseOrderId': null,
    },
  ]);
  return b;
}

Future<void> _openPurchasing(WidgetTester tester) async {
  await openTab(tester, 'More');
  await tester.tap(find.text('Purchasing'));
  await tester.pumpAndSettle();
}

void main() {
  testWidgets('the owner approves a purchase order with a comment', (tester) async {
    final backend = _backend();
    backend.post('/procurement/purchase-orders/po1/approve', _po('SENT_TO_SUPPLIER'));
    await pumpMerchantApp(tester, backend);
    await _openPurchasing(tester);

    expect(backend.callsTo('GET', '/procurement/purchase-orders').first.queryParameters['status'], ['DRAFT', 'PENDING_APPROVAL', 'REJECTED']);
    expect(find.text('PO-261007-00001'), findsOneWidget);
    expect(find.text('Cowberry Dairy Distributors'), findsOneWidget);

    await tester.tap(find.text('PO-261007-00001'));
    await tester.pumpAndSettle();
    expect(find.text('Set Curd 5 kg Bucket'), findsOneWidget);
    expect(find.text('₹1,417.50'), findsWidgets);

    await tester.tap(find.widgetWithText(FilledButton, 'Approve & send'));
    await tester.pumpAndSettle();
    expect(find.text('Approve PO-261007-00001?'), findsOneWidget);
    await tester.enterText(find.widgetWithText(TextField, 'Comment (optional)'), 'Curd needed for the weekend');
    await tester.tap(find.widgetWithText(FilledButton, 'Approve & send').last);
    await tester.pumpAndSettle();

    expect(backend.lastBody('POST', '/procurement/purchase-orders/po1/approve'), {'comment': 'Curd needed for the weekend'});
    expect(find.text('PO-261007-00001: sent to supplier'), findsOneWidget);
    expect(backend.callsTo('GET', '/procurement/purchase-orders/po1').length, greaterThanOrEqualTo(2)); // reloaded
  });

  testWidgets('a manager sees the PO but cannot approve it', (tester) async {
    await pumpMerchantApp(tester, _backend(), accessToken: merchantToken(role: 'MANAGER'));
    await _openPurchasing(tester);
    await tester.tap(find.text('PO-261007-00001'));
    await tester.pumpAndSettle();

    expect(find.text('Approve & send'), findsNothing);
    expect(find.text('Only the owner can approve purchase orders.'), findsOneWidget);
    expect(find.text('Cancel PO'), findsOneWidget); // procurement:manage
  });

  testWidgets('reorder alerts list for the outlet; kitchen roles have no purchasing', (tester) async {
    final backend = _backend();
    await pumpMerchantApp(tester, backend);
    await _openPurchasing(tester);
    await tester.tap(find.text('Alerts'));
    await tester.pumpAndSettle();

    expect(find.text('Tomato'), findsOneWidget);
    expect(find.text('Critical'), findsOneWidget);
    expect(find.text('15.18 kg'), findsOneWidget);
    expect(backend.callsTo('GET', '/procurement/alerts').last.queryParameters['outletId'], 'o1');
  });

  testWidgets('chefs do not get the purchasing screen', (tester) async {
    await pumpMerchantApp(tester, _backend(), accessToken: merchantToken(role: 'CHEF'));
    await openTab(tester, 'More');
    expect(find.text('Purchasing'), findsNothing);
    expect(find.text("Today's sales"), findsNothing);
    expect(find.text('Inventory'), findsOneWidget);
  });
}
