/**
 * Derives the API gateway routing table from the generated OpenAPI specs
 * (docs/api/*.json — run `pnpm docs:openapi` first), so routing always
 * matches the routes the services actually expose.
 *
 *   pnpm gateway:routes
 *
 * Writes:
 *   infrastructure/gateway/routes.json     consumed by scripts/dev-gateway.ts and Helm
 *   infrastructure/docker/nginx/gateway.conf   nginx config for docker-compose
 *
 * A first path segment owned by several services (e.g. /admin) is split on
 * its second segment; any prefix still claimed twice fails the build.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(__dirname, '..');
const API_DIR = path.join(root, 'docs', 'api');

export const SERVICE_PORTS: Record<string, number> = {
  'auth-service': 4001, 'user-service': 4002, 'order-service': 4003, 'payment-service': 4004, 'inventory-service': 4005, 'procurement-service': 4006,
  'delivery-service': 4007, 'supplier-service': 4008, 'analytics-service': 4009, 'ads-service': 4010, 'notification-service': 4011, 'ai-service': 4012,
};

interface Route { prefix: string; service: string; websocket?: boolean }

function main() {
  const owners = new Map<string, Set<string>>();
  const claim = (prefix: string, service: string) => owners.set(prefix, (owners.get(prefix) ?? new Set()).add(service));
  const paths = new Map<string, string[]>();
  for (const file of readdirSync(API_DIR).filter((f) => f.endsWith('-service.json'))) {
    const service = file.replace(/\.json$/, '');
    paths.set(service, Object.keys((JSON.parse(readFileSync(path.join(API_DIR, file), 'utf8')) as { paths: object }).paths));
  }
  // first pass: first segment after /api/v1
  for (const [service, list] of paths) {
    for (const p of list) {
      const segs = p.split('/').filter(Boolean);
      if (segs[0] !== 'api') claim(`/${segs.join('/')}`, service);
      else if (segs[2] && segs[2] !== 'internal') claim(`/api/v1/${segs[2]}`, service);
    }
  }
  // shared first segments are routed on their second segment
  const shared = [...owners].filter(([, s]) => s.size > 1).map(([p]) => p);
  for (const prefix of shared) {
    owners.delete(prefix);
    for (const [service, list] of paths) {
      for (const p of list) {
        if (!p.startsWith(`${prefix}/`)) continue;
        const next = p.slice(prefix.length + 1).split('/')[0]!;
        claim(`${prefix}/${next}`, service);
      }
    }
  }
  const conflicts = [...owners].filter(([, s]) => s.size > 1);
  if (conflicts.length) {
    throw new Error(`Ambiguous gateway prefixes:\n${conflicts.map(([p, s]) => `  ${p}: ${[...s].join(', ')}`).join('\n')}`);
  }
  const routes: Route[] = [...owners].map(([prefix, s]) => ({ prefix, service: [...s][0]! }));
  routes.push({ prefix: '/ws', service: 'delivery-service', websocket: true });
  routes.sort((a, b) => b.prefix.length - a.prefix.length || a.prefix.localeCompare(b.prefix));

  const table = {
    $comment: 'Generated by scripts/generate-gateway-routes.ts from docs/api — do not edit by hand.',
    blocked: ['/api/v1/internal'],
    services: Object.fromEntries(Object.entries(SERVICE_PORTS).map(([name, port]) => [name, { port }])),
    routes,
  };
  writeFileSync(path.join(root, 'infrastructure', 'gateway', 'routes.json'), `${JSON.stringify(table, null, 2)}\n`);
  writeFileSync(path.join(root, 'infrastructure', 'docker', 'nginx', 'gateway.conf'), nginx(routes));
  console.log(`Gateway: ${routes.length} routes across ${new Set(routes.map((r) => r.service)).size} services`);
}

function nginx(routes: Route[]): string {
  const upstreams = Object.entries(SERVICE_PORTS).map(([name, port]) => `upstream ${name.replace(/-/g, '_')} {\n  server ${name}:${port};\n  keepalive 32;\n}`);
  const locations = routes.map((r) => {
    const up = r.service.replace(/-/g, '_');
    const exact = r.prefix.includes('.well-known');
    const loc = exact ? `location = ${r.prefix}` : `location ^~ ${r.prefix}`;
    const ws = r.websocket ? '\n    proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection $connection_upgrade;\n    proxy_read_timeout 1h;' : '';
    return `  ${loc} {\n    proxy_pass http://${up};${ws}\n  }`;
  });
  return `# Generated by scripts/generate-gateway-routes.ts from docs/api — do not edit by hand.
${upstreams.join('\n\n')}

map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/m;
limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;

server {
  listen 8080;
  client_max_body_size 10m;

  proxy_http_version 1.1;
  proxy_set_header Connection "";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Request-Id $request_id;
  add_header X-Request-Id $request_id always;

  # service-to-service routes are never reachable from outside
  location ^~ /api/v1/internal { return 404; }

  location = /healthz { return 200 "ok\\n"; }

  # OTP and password login are rate limited per client IP
  location ~ ^/api/v1/auth/(otp/request|password)$ {
    limit_req zone=auth burst=5 nodelay;
    proxy_pass http://auth_service;
  }

${locations.join('\n\n')}

  location / { return 404; }
}
`;
}

main();
