/**
 * Derives the API gateway routing table from the generated OpenAPI specs
 * (docs/api/*.json — run `pnpm docs:openapi` first), so routing always
 * matches the routes the services actually expose.
 *
 *   pnpm gateway:routes
 *
 * Writes:
 *   infrastructure/gateway/routes.json     consumed by scripts/dev-gateway.ts and Helm
 *   infrastructure/docker/nginx/gateway.conf   nginx config for docker-compose
 *   vercel.json                            Vercel services, public rewrites and bindings
 *   packages/auth/src/next/api-routes.ts   which service owns an API path (web apps on Vercel)
 *
 * A first path segment owned by several services (e.g. /admin) is split on
 * its second segment; any prefix still claimed twice fails the build.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(__dirname, '..');
const API_DIR = path.join(root, 'docs', 'api');

export const SERVICE_PORTS: Record<string, number> = {
  'auth-service': 4001,
  'user-service': 4002,
  'order-service': 4003,
  'payment-service': 4004,
  'inventory-service': 4005,
  'procurement-service': 4006,
  'delivery-service': 4007,
  'supplier-service': 4008,
  'analytics-service': 4009,
  'ads-service': 4010,
  'notification-service': 4011,
  'ai-service': 4012,
};

/** Web apps and the subdomain each one answers on (same hosts as the Kubernetes ingress). */
const WEB_APPS: Record<string, string | null> = {
  'admin-web': 'admin',
  'restaurant-web': 'partner',
  'vendor-web': 'business',
  'supplier-web': 'supplier',
  'rider-web': 'rider',
  'customer-web': null, // every other host: foodgrid.in, www., api. and preview URLs
};

/**
 * Service-to-service HTTP calls (InternalHttpService and DirectoryService), caller → callees.
 * Each becomes a Vercel binding that sets <CALLEE>_SERVICE_URL, the variable the code reads.
 */
const CALLS: Record<string, string[]> = {
  'ads-service': ['order', 'supplier', 'user'],
  'ai-service': ['inventory', 'order'],
  'analytics-service': ['ai', 'delivery', 'order', 'user'],
  'auth-service': ['notification'],
  'delivery-service': ['ai', 'notification', 'order', 'user'],
  'inventory-service': ['order'],
  'notification-service': ['user'],
  'order-service': ['ads', 'ai', 'delivery', 'user'],
  'payment-service': ['ads', 'delivery', 'order', 'supplier', 'user'],
  'procurement-service': ['ai', 'inventory', 'order', 'supplier', 'user'],
  'supplier-service': ['user'],
  'user-service': ['auth', 'notification'],
};

interface Route {
  prefix: string;
  service: string;
  websocket?: boolean;
}

function main() {
  const owners = new Map<string, Set<string>>();
  const claim = (prefix: string, service: string) =>
    owners.set(prefix, (owners.get(prefix) ?? new Set()).add(service));
  const paths = new Map<string, string[]>();
  for (const file of readdirSync(API_DIR).filter((f) => f.endsWith('-service.json'))) {
    const service = file.replace(/\.json$/, '');
    paths.set(
      service,
      Object.keys(
        (JSON.parse(readFileSync(path.join(API_DIR, file), 'utf8')) as { paths: object }).paths,
      ),
    );
  }
  // first pass: first segment after /api/v1
  for (const [service, list] of paths) {
    for (const p of list) {
      const segs = p.split('/').filter(Boolean);
      if (segs[0] !== 'api') claim(`/${segs.join('/')}`, service);
      else if (segs[2] && segs[2] !== 'internal') claim(`/api/v1/${segs[2]}`, service);
    }
  }
  // shared first segments are routed on their second segment
  const shared = [...owners].filter(([, s]) => s.size > 1).map(([p]) => p);
  for (const prefix of shared) {
    owners.delete(prefix);
    for (const [service, list] of paths) {
      for (const p of list) {
        if (!p.startsWith(`${prefix}/`)) continue;
        const next = p.slice(prefix.length + 1).split('/')[0]!;
        claim(`${prefix}/${next}`, service);
      }
    }
  }
  const conflicts = [...owners].filter(([, s]) => s.size > 1);
  if (conflicts.length) {
    throw new Error(
      `Ambiguous gateway prefixes:\n${conflicts.map(([p, s]) => `  ${p}: ${[...s].join(', ')}`).join('\n')}`,
    );
  }
  const routes: Route[] = [...owners].map(([prefix, s]) => ({ prefix, service: [...s][0]! }));
  routes.push({ prefix: '/ws', service: 'delivery-service', websocket: true });
  routes.sort((a, b) => b.prefix.length - a.prefix.length || a.prefix.localeCompare(b.prefix));

  const table = {
    $comment:
      'Generated by scripts/generate-gateway-routes.ts from docs/api — do not edit by hand.',
    blocked: ['/api/v1/internal'],
    services: Object.fromEntries(
      Object.entries(SERVICE_PORTS).map(([name, port]) => [name, { port }]),
    ),
    routes,
  };
  writeFileSync(
    path.join(root, 'infrastructure', 'gateway', 'routes.json'),
    `${JSON.stringify(table, null, 2)}\n`,
  );
  writeFileSync(
    path.join(root, 'infrastructure', 'docker', 'nginx', 'gateway.conf'),
    nginx(routes),
  );
  writeFileSync(path.join(root, 'vercel.json'), `${JSON.stringify(vercel(routes), null, 2)}\n`);
  writeFileSync(
    path.join(root, 'packages', 'auth', 'src', 'next', 'api-routes.ts'),
    `// Generated by scripts/generate-gateway-routes.ts from docs/api — do not edit by hand.
/** API path prefix (longest first) → the env var holding the owning service's URL. */
export const API_ROUTES: readonly (readonly [prefix: string, env: string])[] = [
${routes
  .filter((r) => !r.websocket)
  .map((r) => `  ['${r.prefix}', '${envOf(r.service)}'],`)
  .join('\n')}
];
`,
  );
  console.log(
    `Gateway: ${routes.length} routes across ${new Set(routes.map((r) => r.service)).size} services`,
  );
}

/** auth-service → AUTH_SERVICE_URL (InternalHttpService and the web apps read these). */
const envOf = (service: string) => `${service.replace(/-service$/, '').toUpperCase()}_SERVICE_URL`;

const binding = (service: string) => ({
  type: 'service',
  service,
  format: 'url',
  env: envOf(service),
});

/**
 * One Vercel project: every web app and API service is a Vercel service. /api/v1 routes go
 * to the owning service on any host (the mobile apps call them directly); every other path
 * goes to the web app for the request's subdomain. Service-to-service calls use bindings.
 */
function vercel(routes: Route[]) {
  const build = (pkg: string) => `cd ../.. && pnpm turbo run build --filter=@foodgrid/${pkg}...`;
  const services = {
    ...Object.fromEntries(
      Object.keys(WEB_APPS).map((app) => [
        app,
        {
          root: `apps/${app}`,
          framework: 'nextjs',
          buildCommand: build(app),
          // the API proxy and server components call the API services directly
          bindings: Object.keys(SERVICE_PORTS).map(binding),
        },
      ]),
    ),
    ...Object.fromEntries(
      Object.keys(SERVICE_PORTS).map((svc) => [
        svc,
        {
          root: `services/${svc}`,
          framework: 'nestjs',
          entrypoint: 'src/main.ts',
          buildCommand: build(svc),
          bindings: (CALLS[svc] ?? []).map((callee) => binding(`${callee}-service`)),
        },
      ]),
    ),
  };
  // shortcut: no /ws rewrite: Vercel Functions cannot hold the socket.io connections of
  // delivery-service's tracking gateway; run it on a WebSocket host before relying on live updates
  const api = routes
    .filter((r) => !r.websocket)
    .map((r) => ({
      source: r.prefix.includes('.well-known') ? r.prefix : `${r.prefix}/:path*`,
      destination: { service: r.service },
    }));
  const web = Object.entries(WEB_APPS)
    .sort(([, a], [, b]) => (a === null ? 1 : 0) - (b === null ? 1 : 0))
    .map(([app, sub]) => ({
      source: '/(.*)',
      ...(sub ? { has: [{ type: 'host', value: `${sub}\\..+` }] } : {}),
      destination: { service: app },
    }));
  return { $schema: 'https://openapi.vercel.sh/vercel.json', services, rewrites: [...api, ...web] };
}

function nginx(routes: Route[]): string {
  const upstreams = Object.entries(SERVICE_PORTS).map(
    ([name, port]) =>
      `upstream ${name.replace(/-/g, '_')} {\n  server ${name}:${port};\n  keepalive 32;\n}`,
  );
  const locations = routes.map((r) => {
    const up = r.service.replace(/-/g, '_');
    const exact = r.prefix.includes('.well-known');
    const loc = exact ? `location = ${r.prefix}` : `location ^~ ${r.prefix}`;
    const ws = r.websocket
      ? '\n    proxy_set_header Upgrade $http_upgrade;\n    proxy_set_header Connection $connection_upgrade;\n    proxy_read_timeout 1h;'
      : '';
    return `  ${loc} {\n    proxy_pass http://${up};${ws}\n  }`;
  });
  return `# Generated by scripts/generate-gateway-routes.ts from docs/api — do not edit by hand.
${upstreams.join('\n\n')}

map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/m;
limit_req_zone $binary_remote_addr zone=api:10m rate=30r/s;

server {
  listen 8080;
  client_max_body_size 10m;

  proxy_http_version 1.1;
  proxy_set_header Connection "";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Request-Id $request_id;
  add_header X-Request-Id $request_id always;

  # service-to-service routes are never reachable from outside
  location ^~ /api/v1/internal { return 404; }

  location = /healthz { return 200 "ok\\n"; }

  # OTP and password login are rate limited per client IP
  location ~ ^/api/v1/auth/(otp/request|password)$ {
    limit_req zone=auth burst=5 nodelay;
    proxy_pass http://auth_service;
  }

${locations.join('\n\n')}

  location / { return 404; }
}
`;
}

main();
