/**
 * Generates OpenAPI 3 documents for every service from the compiled
 * modules (run `pnpm build` first — Nest DI needs the decorator metadata
 * emitted by tsc, which tsx/esbuild does not produce).
 *
 *   pnpm docs:openapi            # writes docs/api/<service>.json + docs/api/README.md
 *
 * No database or Redis is needed: the apps are created but never started.
 */
import 'reflect-metadata';
import { generateKeyPairSync } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

const root = path.resolve(__dirname, '..');
const outDir = path.join(root, 'docs', 'api');

type OpenApi = { info: { title: string; description?: string }; paths: Record<string, Record<string, { summary?: string; tags?: string[]; security?: unknown[] }>> };

function prepareEnv() {
  const { publicKey, privateKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  Object.assign(process.env, {
    NODE_ENV: 'test', // silences request logging
    SWAGGER_ENABLED: 'false',
    DATABASE_URL: process.env.DATABASE_URL ?? 'postgresql://docs:docs@localhost:5432/docs',
    REDIS_URL: process.env.REDIS_URL ?? 'redis://localhost:6379',
    JWT_PUBLIC_KEY_BASE64: Buffer.from(publicKey).toString('base64'),
    JWT_PRIVATE_KEY_BASE64: Buffer.from(privateKey).toString('base64'),
    INTERNAL_SERVICE_SECRET: 'docs-generation',
    OTP_SECRET: 'docs-generation',
    EVENTS_CONSUMER_ENABLED: 'false',
    OUTBOX_RELAY_ENABLED: 'false',
  });
}

async function generate(service: string): Promise<OpenApi> {
  const dir = path.join(root, 'services', service);
  const dist = path.join(dir, 'dist');
  if (!existsSync(path.join(dist, 'app.module.js'))) throw new Error(`${service} is not built — run pnpm build`);
  // resolve framework packages from the service so the compiled module shares their instances
  const req = createRequire(path.join(dir, 'package.json'));
  const { NestFactory } = req('@nestjs/core');
  const { configureApp, buildOpenApiDocument } = req('@foodgrid/utils/server');
  const { AppModule } = req(path.join(dist, 'app.module.js'));
  const { SERVICE } = req(path.join(dist, 'service.config.js'));
  const app = await NestFactory.create(AppModule, { logger: false });
  configureApp(app, SERVICE);
  const doc = buildOpenApiDocument(app, SERVICE) as OpenApi;
  await app.close();
  return doc;
}

function operations(doc: OpenApi) {
  const ops: { method: string; path: string; summary: string; tag: string; auth: string }[] = [];
  for (const [p, methods] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(methods)) {
      const scheme = op.security?.[0] ? Object.keys(op.security[0] as object)[0] : undefined;
      const auth = scheme === 'service-token' ? 'service token' : scheme ? 'bearer' : 'public';
      ops.push({ method: method.toUpperCase(), path: p, summary: op.summary ?? '', tag: op.tags?.[0] ?? '', auth });
    }
  }
  return ops.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

async function main() {
  prepareEnv();
  mkdirSync(outDir, { recursive: true });
  const services = readdirSync(path.join(root, 'services')).filter((d) => d.endsWith('-service')).sort();
  const index: string[] = [
    '# FoodGrid HTTP APIs',
    '',
    'Generated by `pnpm docs:openapi` from the compiled services — do not edit by hand.',
    'Each running service also serves Swagger UI at `/docs` and this JSON at `/docs/json`.',
    '',
    'All routes are prefixed with `/api/v1`. Routes under `/api/v1/internal/*` are service-to-service only (HS256 `x-service-token`) and are blocked at the gateway.',
    '',
    '| Service | Public & user routes | Internal routes | Spec |',
    '| --- | ---: | ---: | --- |',
  ];
  const sections: string[] = [];
  for (const service of services) {
    const doc = await generate(service);
    writeFileSync(path.join(outDir, `${service}.json`), `${JSON.stringify(doc, null, 2)}\n`);
    const ops = operations(doc);
    const internal = ops.filter((o) => o.auth === 'service token');
    index.push(`| ${service} | ${ops.length - internal.length} | ${internal.length} | [${service}.json](./${service}.json) |`);
    sections.push(
      `## ${doc.info.title}`,
      '',
      doc.info.description ?? '',
      '',
      '| Method | Path | Auth | Summary |',
      '| --- | --- | --- | --- |',
      ...ops.map((o) => `| ${o.method} | \`${o.path}\` | ${o.auth} | ${o.summary.replace(/\|/g, '\\|')} |`),
      '',
    );
    console.log(`  • ${service}: ${ops.length} operations`);
  }
  writeFileSync(path.join(outDir, 'README.md'), [...index, '', ...sections].join('\n'));
  console.log(`OpenAPI documents written to ${path.relative(root, outDir)}/`);
  process.exit(0); // nothing should keep running, but never hang CI
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
