import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '@foodgrid/database/nest';
import { generateDocumentNumber, Prisma } from '@foodgrid/database';
import type { PurchaseOrder, PurchaseOrderItem, PurchaseOrderStatus, SupplierStrategy } from '@foodgrid/database';
import {
  AccessTokenClaims,
  AddressSnapshot,
  EventTypes,
  PurchaseOrderEvent,
  PurchaseOrderReceivedEvent,
} from '@foodgrid/types';
import { badRequest, canConvert, computeGst, conflict, convertUnit, money, normalizePage, notFound, paginate, round2, sumMoney, Unit } from '@foodgrid/utils';
import { InternalHttpService, OutboxService } from '@foodgrid/utils/server';
import { ClientsService } from '../clients/clients.service';
import { requiresApproval } from '../domain/assessment';
import { poAmountsFromSupplier, SupplierBilledAmounts } from '../domain/billing';
import { poStateMachine } from '../domain/po-state';
import { RecommendationsService } from '../recommendations/recommendations.service';
import { SettingsService } from '../settings/settings.service';
import { AutoPoDto, CreatePoDto, ListPoDto, ReceivePoDto } from './dto/po.dto';

type Tx = Prisma.TransactionClient;
type PoWithItems = PurchaseOrder & { items: PurchaseOrderItem[] };

interface ProductInfo {
  id: string;
  tenantId: string;
  name: string;
  sku: string;
  unit: string;
  packSize: string;
  price: string;
  gstRate: string;
  deliveryTimeHours: number;
  priceTiers: { minQty: string; unitPrice: string; segment: string }[];
}

interface DraftLine {
  ingredientId: string | null;
  productId: string;
  name: string;
  sku: string | null;
  quantity: number;
  unit: string;
  unitPrice: number;
  gstRate: number;
  baseQtyPerPack: number;
  ingredientUnit: string | null;
  leadTimeHours: number;
}

/**
 * Purchase order lifecycle:
 *   DRAFT → PENDING_APPROVAL (owner) → APPROVED → SENT_TO_SUPPLIER
 *   → CONFIRMED / PARTIALLY_CONFIRMED / SUPPLIER_REJECTED (supplier)
 *   → DISPATCHED → IN_TRANSIT → DELIVERED → (PARTIALLY_)RECEIVED → CLOSED
 */
@Injectable()
export class PurchaseOrdersService {
  private readonly logger = new Logger(PurchaseOrdersService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly outbox: OutboxService,
    private readonly clients: ClientsService,
    private readonly internal: InternalHttpService,
    private readonly recommendations: RecommendationsService,
    private readonly settings: SettingsService,
  ) {}

  // ─── creation ──────────────────────────────────────────────────────────────
  private async createPo(
    tx: Tx,
    p: { tenantId: string; outletId: string; supplierTenantId: string; supplierName: string; lines: DraftLine[]; source: 'MANUAL' | 'AUTO_REORDER'; strategy?: SupplierStrategy | null; createdBy?: string | null; notes?: string | null; paymentTerms?: string; deliveryAddress: AddressSnapshot },
  ) {
    const priced = p.lines.map((l) => {
      const subtotal = round2(l.quantity * l.unitPrice);
      const tax = computeGst(subtotal, l.gstRate, false).totalTax;
      return { ...l, subtotal, tax, lineTotal: round2(subtotal + tax) };
    });
    const subtotal = sumMoney(priced.map((l) => l.subtotal));
    const taxTotal = sumMoney(priced.map((l) => l.tax));
    const lead = Math.max(24, ...priced.map((l) => l.leadTimeHours));
    return tx.purchaseOrder.create({
      data: {
        poNumber: await generateDocumentNumber(tx, 'PO'),
        tenantId: p.tenantId,
        outletId: p.outletId,
        supplierTenantId: p.supplierTenantId,
        supplierName: p.supplierName,
        source: p.source,
        strategy: p.strategy ?? undefined,
        subtotal,
        taxTotal,
        total: round2(subtotal + taxTotal),
        paymentTerms: p.paymentTerms ?? 'PREPAID',
        expectedDeliveryAt: new Date(Date.now() + lead * 3_600_000),
        deliveryAddress: p.deliveryAddress as unknown as Prisma.InputJsonValue,
        notes: p.notes,
        createdBy: p.createdBy,
        items: {
          create: priced.map((l) => ({
            ingredientId: l.ingredientId,
            productId: l.productId,
            name: l.name,
            sku: l.sku,
            quantity: l.quantity,
            unit: l.unit,
            unitPrice: l.unitPrice,
            gstRate: l.gstRate,
            taxAmount: l.tax,
            lineTotal: l.lineTotal,
            baseQtyPerPack: l.baseQtyPerPack,
            ingredientUnit: l.ingredientUnit,
          })),
        },
        events: { create: { status: 'DRAFT', note: p.source === 'AUTO_REORDER' ? 'Generated by the smart procurement engine' : 'Created', actorType: p.createdBy ? 'USER' : 'SYSTEM', actorId: p.createdBy } },
      },
      include: { items: true },
    });
  }

  /** Manual PO for specific marketplace products. */
  async createManual(user: AccessTokenClaims, dto: CreatePoDto) {
    const tenantId = user.tenantId!;
    const outlet = await this.clients.outlet(dto.outletId);
    if (outlet.tenantId !== tenantId) throw notFound('Outlet', dto.outletId);
    const lines: DraftLine[] = [];
    let supplierName = 'Supplier';
    for (const item of dto.items) {
      const p = await this.internal.get<ProductInfo>('supplier', `internal/marketplace/products/${item.productId}`);
      if (p.tenantId !== dto.supplierTenantId) throw badRequest(`${p.name} is not sold by this supplier`, 'SUPPLIER_MISMATCH');
      const ing = item.ingredientId ? await this.clients.ingredient(item.ingredientId) : null;
      if (ing && ing.tenantId !== tenantId) throw notFound('Ingredient', item.ingredientId!);
      const tier = p.priceTiers
        .filter((t) => (t.segment === 'ALL' || t.segment === 'RESTAURANT') && Number(t.minQty) <= item.quantity)
        .sort((a, b) => Number(b.minQty) - Number(a.minQty))[0];
      lines.push({
        ingredientId: item.ingredientId ?? null,
        productId: p.id,
        name: p.name,
        sku: p.sku,
        quantity: item.quantity,
        unit: `${Number(p.packSize)} ${p.unit}`,
        unitPrice: tier ? Number(tier.unitPrice) : Number(p.price),
        gstRate: Number(p.gstRate),
        baseQtyPerPack: ing ? convertPack(Number(p.packSize), p.unit, ing.unit) : Number(p.packSize),
        ingredientUnit: ing?.unit ?? null,
        leadTimeHours: p.deliveryTimeHours,
      });
    }
    const supplier = await this.internal.get<{ name: string }>('user', `internal/tenants/${dto.supplierTenantId}`).catch(() => null);
    supplierName = supplier?.name ?? supplierName;
    return this.prisma.$transaction((tx) =>
      this.createPo(tx, {
        tenantId,
        outletId: dto.outletId,
        supplierTenantId: dto.supplierTenantId,
        supplierName,
        lines,
        source: 'MANUAL',
        createdBy: user.sub,
        notes: dto.notes,
        paymentTerms: dto.paymentTerms,
        deliveryAddress: this.clients.outletAddress(outlet),
      }),
    );
  }

  /**
   * Auto-PO: picks the best supplier per open alert (tenant default strategy),
   * groups lines by (outlet, supplier) and routes each PO through approval —
   * or straight to the supplier when it is within the auto-approve limit.
   */
  async autoCreate(tenantId: string, actorId: string | null, dto: AutoPoDto = {}) {
    const settings = await this.settings.get(tenantId);
    const alerts = await this.prisma.forTenant(tenantId).reorderAlert.findMany({
      where: { status: 'OPEN', ...(dto.alertIds?.length ? { id: { in: dto.alertIds } } : {}) },
    });
    const groups = new Map<string, { outletId: string; supplierTenantId: string; supplierName: string; lines: DraftLine[]; alertIds: string[] }>();
    const skipped: { alertId: string; ingredient: string; reason: string }[] = [];
    for (const alert of alerts) {
      try {
        const best = await this.recommendations.bestOption(tenantId, alert.ingredientId, Number(alert.suggestedQty), dto.strategy ?? settings.defaultStrategy);
        if (!best) {
          skipped.push({ alertId: alert.id, ingredient: alert.ingredientName, reason: 'No serviceable supplier in stock' });
          continue;
        }
        const key = `${alert.outletId}:${best.supplierTenantId}`;
        const g = groups.get(key) ?? { outletId: alert.outletId, supplierTenantId: best.supplierTenantId, supplierName: best.supplierName, lines: [], alertIds: [] };
        g.lines.push({
          ingredientId: alert.ingredientId,
          productId: best.productId,
          name: best.productName,
          sku: null,
          quantity: best.packs,
          unit: `${best.packSize} ${alert.unit}`,
          unitPrice: best.unitPrice,
          gstRate: best.subtotal > 0 ? round2((best.tax / best.subtotal) * 100) : 0,
          baseQtyPerPack: best.packSize,
          ingredientUnit: alert.unit,
          leadTimeHours: best.leadTimeHours,
        });
        g.alertIds.push(alert.id);
        groups.set(key, g);
      } catch (err) {
        skipped.push({ alertId: alert.id, ingredient: alert.ingredientName, reason: (err as Error).message });
      }
    }

    const created: PoWithItems[] = [];
    for (const g of groups.values()) {
      const outlet = await this.clients.outlet(g.outletId);
      const po = await this.prisma.$transaction(async (tx) => {
        const po = await this.createPo(tx, {
          tenantId,
          outletId: g.outletId,
          supplierTenantId: g.supplierTenantId,
          supplierName: g.supplierName,
          lines: g.lines,
          source: 'AUTO_REORDER',
          strategy: dto.strategy ?? settings.defaultStrategy,
          createdBy: actorId,
          deliveryAddress: this.clients.outletAddress(outlet),
        });
        await tx.reorderAlert.updateMany({ where: { id: { in: g.alertIds } }, data: { status: 'PO_CREATED', purchaseOrderId: po.id } });
        if (requiresApproval(Number(po.total), Number(settings.autoApproveBelow))) {
          return this.transitionInTx(tx, po.id, 'PENDING_APPROVAL', { submittedAt: new Date() }, 'Awaiting owner approval', null);
        }
        await this.transitionInTx(tx, po.id, 'APPROVED', { approvedAt: new Date(), approvedBy: 'auto' }, `Auto-approved (≤ ₹${Number(settings.autoApproveBelow)})`, null);
        return this.transitionInTx(tx, po.id, 'SENT_TO_SUPPLIER', { sentAt: new Date() }, 'Sent to supplier', null);
      });
      created.push(po);
    }
    return {
      created: created.map((p) => ({ id: p.id, poNumber: p.poNumber, supplierName: p.supplierName, total: p.total, status: p.status, items: p.items.length })),
      skipped,
    };
  }

  // ─── workflow ──────────────────────────────────────────────────────────────
  private async transitionInTx(tx: Tx, id: string, to: PurchaseOrderStatus, data: Prisma.PurchaseOrderUpdateInput, note: string | null, actorId: string | null, loc?: { lat?: number; lng?: number }) {
    await tx.$queryRaw`SELECT id FROM "procurement"."PurchaseOrder" WHERE id = ${id} FOR UPDATE`;
    const po = await tx.purchaseOrder.findUniqueOrThrow({ where: { id } });
    if (po.status === to && to !== 'IN_TRANSIT') return tx.purchaseOrder.findUniqueOrThrow({ where: { id }, include: { items: true } });
    poStateMachine.assert(po.status, to);
    const updated = await tx.purchaseOrder.update({
      where: { id },
      data: { ...data, status: to, events: { create: { status: to, note, actorId, actorType: actorId ? 'USER' : 'SYSTEM', lat: loc?.lat, lng: loc?.lng } } },
      include: { items: true },
    });
    await this.emitFor(tx, updated, note);
    return updated;
  }

  private async emitFor(tx: Tx, po: PoWithItems, note: string | null) {
    const type =
      po.status === 'PENDING_APPROVAL'
        ? EventTypes.PurchaseOrderSubmitted
        : po.status === 'SENT_TO_SUPPLIER'
          ? EventTypes.PurchaseOrderApproved
          : po.status === 'REJECTED'
            ? EventTypes.PurchaseOrderRejected
            : po.status === 'CANCELLED'
              ? EventTypes.PurchaseOrderCancelled
              : null;
    if (!type) return;
    const buyer = (po.deliveryAddress as AddressSnapshot | null)?.contactName ?? 'Restaurant';
    await this.outbox.enqueue<PurchaseOrderEvent>(tx, {
      stream: 'procurement',
      type,
      aggregateType: 'PurchaseOrder',
      aggregateId: po.id,
      tenantId: po.tenantId,
      data: {
        purchaseOrderId: po.id,
        poNumber: po.poNumber,
        tenantId: po.tenantId,
        buyerName: buyer,
        outletId: po.outletId,
        supplierTenantId: po.supplierTenantId,
        status: po.status,
        total: money(po.total.toString()),
        paymentTerms: po.paymentTerms,
        expectedDeliveryAt: po.expectedDeliveryAt?.toISOString() ?? null,
        deliveryAddress: (po.deliveryAddress as AddressSnapshot | null) ?? null,
        items: po.items.map((i) => ({
          ingredientId: i.ingredientId,
          productId: i.productId,
          name: i.name,
          sku: i.sku,
          quantity: i.quantity.toString(),
          unit: i.unit,
          unitPrice: money(i.unitPrice.toString()),
          gstRate: i.gstRate.toString(),
        })),
        notes: note ?? po.notes,
      },
    });
  }

  private async owned(tenantId: string, id: string) {
    const po = await this.prisma.forTenant(tenantId).purchaseOrder.findUnique({ where: { id } });
    if (!po) throw notFound('Purchase order', id);
    return po;
  }

  async submit(user: AccessTokenClaims, id: string) {
    const po = await this.owned(user.tenantId!, id);
    const settings = await this.settings.get(user.tenantId!);
    return this.prisma.$transaction(async (tx) => {
      if (!requiresApproval(Number(po.total), Number(settings.autoApproveBelow))) {
        await this.transitionInTx(tx, id, 'APPROVED', { approvedAt: new Date(), approvedBy: 'auto' }, 'Within auto-approval limit', user.sub);
        return this.transitionInTx(tx, id, 'SENT_TO_SUPPLIER', { sentAt: new Date() }, 'Sent to supplier', user.sub);
      }
      return this.transitionInTx(tx, id, 'PENDING_APPROVAL', { submittedAt: new Date() }, 'Submitted for approval', user.sub);
    });
  }

  /** Restaurant owner approval → the PO is sent to the supplier immediately. */
  async approve(user: AccessTokenClaims, id: string, comment?: string) {
    await this.owned(user.tenantId!, id);
    return this.prisma.$transaction(async (tx) => {
      await tx.purchaseOrderApproval.create({ data: { purchaseOrderId: id, approverId: user.sub, decision: 'APPROVED', comment } });
      await this.transitionInTx(tx, id, 'APPROVED', { approvedAt: new Date(), approvedBy: user.sub }, comment ?? 'Approved', user.sub);
      return this.transitionInTx(tx, id, 'SENT_TO_SUPPLIER', { sentAt: new Date() }, 'Sent to supplier', user.sub);
    });
  }

  async reject(user: AccessTokenClaims, id: string, comment?: string) {
    await this.owned(user.tenantId!, id);
    return this.prisma.$transaction(async (tx) => {
      await tx.purchaseOrderApproval.create({ data: { purchaseOrderId: id, approverId: user.sub, decision: 'REJECTED', comment } });
      const po = await this.transitionInTx(tx, id, 'REJECTED', { rejectedReason: comment }, comment ?? 'Rejected', user.sub);
      await tx.reorderAlert.updateMany({ where: { purchaseOrderId: id }, data: { status: 'OPEN', purchaseOrderId: null } });
      return po;
    });
  }

  async cancel(user: AccessTokenClaims, id: string, reason?: string) {
    const po = await this.owned(user.tenantId!, id);
    if (['DISPATCHED', 'IN_TRANSIT', 'DELIVERED', 'RECEIVED', 'PARTIALLY_RECEIVED'].includes(po.status)) {
      throw conflict('The supplier has already shipped this order', 'PO_SHIPPED');
    }
    return this.prisma.$transaction(async (tx) => {
      const updated = await this.transitionInTx(tx, id, 'CANCELLED', {}, reason ?? 'Cancelled', user.sub);
      await tx.reorderAlert.updateMany({ where: { purchaseOrderId: id }, data: { status: 'OPEN', purchaseOrderId: null } });
      return updated;
    });
  }

  /** Goods receipt (GRN) — stock is added by inventory-service on procurement.po.received. */
  async receive(user: AccessTokenClaims, id: string, dto: ReceivePoDto) {
    const po = await this.prisma.forTenant(user.tenantId!).purchaseOrder.findUnique({ where: { id }, include: { items: true } });
    if (!po) throw notFound('Purchase order', id);
    const byId = new Map(po.items.map((i) => [i.id, i]));
    for (const l of dto.lines) if (!byId.has(l.itemId)) throw badRequest(`Unknown line ${l.itemId}`, 'INVALID_LINE');

    return this.prisma.$transaction(async (tx) => {
      for (const l of dto.lines) {
        await tx.purchaseOrderItem.update({ where: { id: l.itemId }, data: { receivedQty: { increment: l.receivedQty } } });
      }
      const items = await tx.purchaseOrderItem.findMany({ where: { purchaseOrderId: id } });
      const complete = items.every((i) => Number(i.receivedQty) >= Number(i.confirmedQty ?? i.quantity));
      const to: PurchaseOrderStatus = complete ? 'RECEIVED' : 'PARTIALLY_RECEIVED';
      const updated = await this.transitionInTx(tx, id, to, { receivedAt: new Date(), receivedBy: user.sub }, dto.note ?? 'Goods received', user.sub);
      const lines = dto.lines
        .map((l) => ({ line: l, item: byId.get(l.itemId)! }))
        .filter(({ line, item }) => line.receivedQty > 0 && item.ingredientId)
        .map(({ line, item }) => ({
          ingredientId: item.ingredientId!,
          receivedQty: String(round2(line.receivedQty * Number(item.baseQtyPerPack))),
          unitPrice: money(Number(item.unitPrice) / Number(item.baseQtyPerPack || 1)),
          unit: item.ingredientUnit ?? item.unit,
        }));
      await this.outbox.enqueue<PurchaseOrderReceivedEvent>(tx, {
        stream: 'procurement',
        type: EventTypes.PurchaseOrderReceived,
        aggregateType: 'PurchaseOrder',
        aggregateId: id,
        tenantId: po.tenantId,
        data: { purchaseOrderId: id, poNumber: po.poNumber, tenantId: po.tenantId, outletId: po.outletId, supplierTenantId: po.supplierTenantId, lines },
      });
      await tx.reorderAlert.updateMany({ where: { purchaseOrderId: id }, data: { status: 'RESOLVED', resolvedAt: new Date() } });
      return updated;
    });
  }

  // ─── supplier-side updates (from marketplace events) ──────────────────────
  async applySupplierUpdate(
    poId: string,
    update: {
      status: PurchaseOrderStatus;
      note?: string | null;
      supplierOrderId?: string;
      confirmedLines?: { productId: string; confirmedQty: string }[];
      tracking?: Record<string, unknown> | null;
      expectedDeliveryAt?: string | null;
      /** Amounts as billed by the supplier (dealer discount, freight GST); they supersede the PO estimate. */
      billed?: SupplierBilledAmounts | null;
    },
  ) {
    return this.prisma.$transaction(async (tx) => {
      const po = await tx.purchaseOrder.findUnique({ where: { id: poId }, include: { items: true } });
      if (!po) return null;
      if (update.confirmedLines) {
        for (const line of update.confirmedLines) {
          const item = po.items.find((i) => i.productId === line.productId);
          if (item) await tx.purchaseOrderItem.update({ where: { id: item.id }, data: { confirmedQty: Number(line.confirmedQty) } });
        }
      }
      const now = new Date();
      const data: Prisma.PurchaseOrderUpdateInput = {
        ...(update.supplierOrderId ? { supplierOrderId: update.supplierOrderId } : {}),
        ...(update.status === 'CONFIRMED' || update.status === 'PARTIALLY_CONFIRMED' ? { supplierConfirmedAt: now, supplierNotes: update.note } : {}),
        ...(update.status === 'SUPPLIER_REJECTED' ? { supplierNotes: update.note } : {}),
        ...(update.status === 'DISPATCHED' ? { dispatchedAt: now } : {}),
        ...(update.status === 'DELIVERED' ? { deliveredAt: now } : {}),
        ...(update.tracking ? { trackingInfo: update.tracking as Prisma.InputJsonValue } : {}),
        ...(update.expectedDeliveryAt ? { expectedDeliveryAt: new Date(update.expectedDeliveryAt) } : {}),
        ...(update.billed ? poAmountsFromSupplier(update.billed) : {}),
      };
      if (!poStateMachine.can(po.status, update.status)) {
        if (Object.keys(data).length) await tx.purchaseOrder.update({ where: { id: poId }, data });
        return po;
      }
      const loc = update.tracking && typeof update.tracking.lat === 'number' ? { lat: update.tracking.lat as number, lng: update.tracking.lng as number } : undefined;
      const updated = await this.transitionInTx(tx, poId, update.status, data, update.note ?? null, null, loc);
      if (update.status === 'SUPPLIER_REJECTED') {
        await tx.reorderAlert.updateMany({ where: { purchaseOrderId: poId }, data: { status: 'OPEN', purchaseOrderId: null } });
      }
      return updated;
    });
  }

  // ─── queries ───────────────────────────────────────────────────────────────
  async list(tenantId: string, q: ListPoDto) {
    const { page, pageSize, skip, take } = normalizePage(q);
    const where: Prisma.PurchaseOrderWhereInput = {
      ...(q.status?.length ? { status: { in: q.status } } : {}),
      outletId: q.outletId,
      supplierTenantId: q.supplierTenantId,
    };
    const db = this.prisma.forTenant(tenantId);
    const [rows, total] = await Promise.all([
      db.purchaseOrder.findMany({ where, orderBy: { createdAt: 'desc' }, skip, take, include: { items: true } }),
      db.purchaseOrder.count({ where }),
    ]);
    return paginate(rows, total, page, pageSize);
  }

  async get(tenantId: string, id: string) {
    const po = await this.prisma.forTenant(tenantId).purchaseOrder.findUnique({
      where: { id },
      include: { items: true, approvals: true, events: { orderBy: { createdAt: 'asc' } } },
    });
    if (!po) throw notFound('Purchase order', id);
    return po;
  }
}

/** Pack size of a marketplace product expressed in the ingredient's stock unit. */
function convertPack(packSize: number, from: string, to: string): number {
  return canConvert(from as Unit, to as Unit) ? convertUnit(packSize, from as Unit, to as Unit) : packSize;
}
